
name: CI Pipeline

on:
  pull_request:
    branches: [develop, main]

jobs:
  lint:
    name: 🧪 SwiftLint
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint --config .swiftlint.yml

  format:
    name: 🧹 SwiftFormat Check
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Run SwiftFormat dry-run
        run: swiftformat . --dryrun --swiftversion 6.0

  tests:
    name: 🧪 Unit Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run Unit Tests
        run: |
          xcodebuild test -scheme "Smart City"             -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'             ONLY_ACTIVE_ARCH=NO             -enableCodeCoverage YES
