name: CI Pipeline

on:
  pull_request:
    branches: [develop, main]

jobs:
  lint:
    name: 🧹 SwiftLint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint --config .swiftlint.yml

  format:
    name: 🧹 SwiftFormat Check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SwiftFormat
        run: brew install swiftformat
      - name: Run SwiftFormat dry-run
        run: swiftformat . --dryrun --swiftversion 6.0

  test:
    name: 🧪 Build & Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install xcpretty
        run: gem install xcpretty --no-document

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Build & Run All Tests
        run: |
          xcodebuild test \
            -workspace "Smart City.xcworkspace" \
            -scheme "Smart City" \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=latest" \
            ONLY_ACTIVE_ARCH=NO \
            -enableCodeCoverage YES \
          | xcpretty --color