name: SwiftFormat Check

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  swiftformat:
    name: 🧹 SwiftFormat Verification
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Run SwiftFormat dry-run
        run: |
          swiftformat . --dryrun --swiftversion 6.0