
name: Run Tests

on:
  pull_request:
    branches: [develop, main]

jobs:
  test:
    name: 🧪 Unit Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Show available Xcode version
        run: xcodebuild -version

      - name: Run Unit Tests
        run: |
          xcodebuild test -scheme "Smart City"             -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'             ONLY_ACTIVE_ARCH=NO             -enableCodeCoverage YES
